x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m
    cpus: "1.0"
    <<: *default-logging
    restart: unless-stopped

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_packages:/piston/packages
    tmpfs:
      - /tmp:exec
    mem_limit: 2g
    cpus: "1.0"
    <<: *default-logging

volumes:
  postgres_data:
  piston_packages:
